apiVersion: v1
kind: Secret
metadata:
  name: santricity-csi-credentials
  namespace: kube-system
type: Opaque
stringData:
  # Using stringData for convenience in this example. 
  # In real usage, use 'data' with base64 encoded values.
  username: "admin"
  password: "process_password_here"
  # endpoint: "https://10.10.10.10:8443/devmgr/v2" # Optional: Can be moved here too if desired
